manifest:
  self:
    path: akadimia-sdk
    
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyr
      import: true
