manifest:
  self:
    path: akadimia-sdk
    
  remotes:
    - name: akadimia-sdk
      url-base: https://github.com/liangyongqin
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyr
      revision: v4.0.0
